name:  Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ gap_builds ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Fetch bundle compiler
        run: ./gradlew clean getBundled
        working-directory: ./kotlin-bundled-compiler
        
      - name: Build with Maven
        run: mvn install -DskipTests
        
      - name: Deploy p2 site
        if: ${{ github.ref == 'refs/heads/gap_builds' }}
        run: |
          git config user.email "workflows@egithub.com"
          git config user.name "workflows@egithub.com"
          mkdir -p ./p2/
          cp -r ./kotlin-eclipse-p2updatesite/target/repository ./p2/nightly
          git add -f ./p2/nightly/*
          git stash
          git fetch --all
          git checkout --track origin/gh-pages
          git rm -rf --ignore-unmatch ./p2/nightly/*
          git clean -df
          git stash pop
          git add -f ./p2/nightly/*
          git commit -m "Deploy artifacts to p2 update site"
          git push origin gh-pages
          git switch main
          echo "Deployed successfully"
